# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ej3b/readoutsys/rtos_sys/rtos_sys.srcs/sources_1/bd/rtos_sys/ip/rtos_sys_axi_dma_1_0/rtos_sys_axi_dma_1_0.xci
# IP: The module: 'rtos_sys_axi_dma_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ej3b/readoutsys/rtos_sys/rtos_sys.gen/sources_1/bd/rtos_sys/ip/rtos_sys_axi_dma_1_0/rtos_sys_axi_dma_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'rtos_sys_axi_dma_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/ej3b/readoutsys/rtos_sys/rtos_sys.gen/sources_1/bd/rtos_sys/ip/rtos_sys_axi_dma_1_0/rtos_sys_axi_dma_1_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'rtos_sys_axi_dma_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/ej3b/readoutsys/rtos_sys/rtos_sys.gen/sources_1/bd/rtos_sys/ip/rtos_sys_axi_dma_1_0/rtos_sys_axi_dma_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rtos_sys_axi_dma_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/ej3b/readoutsys/rtos_sys/rtos_sys.srcs/sources_1/bd/rtos_sys/ip/rtos_sys_axi_dma_1_0/rtos_sys_axi_dma_1_0.xci
# IP: The module: 'rtos_sys_axi_dma_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ej3b/readoutsys/rtos_sys/rtos_sys.gen/sources_1/bd/rtos_sys/ip/rtos_sys_axi_dma_1_0/rtos_sys_axi_dma_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'rtos_sys_axi_dma_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/ej3b/readoutsys/rtos_sys/rtos_sys.gen/sources_1/bd/rtos_sys/ip/rtos_sys_axi_dma_1_0/rtos_sys_axi_dma_1_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'rtos_sys_axi_dma_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/ej3b/readoutsys/rtos_sys/rtos_sys.gen/sources_1/bd/rtos_sys/ip/rtos_sys_axi_dma_1_0/rtos_sys_axi_dma_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rtos_sys_axi_dma_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
