# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /media/ej3b/a1030d84-846f-4a15-9828-0951444df26f/home/ej3b/Music/Cora-Z7-07S-Master.xdc

# Block Designs: bd/rtos_sys/rtos_sys.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rtos_sys || ORIG_REF_NAME==rtos_sys} -quiet] -quiet

# IP: bd/rtos_sys/ip/rtos_sys_processing_system7_0_0/rtos_sys_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rtos_sys_processing_system7_0_0 || ORIG_REF_NAME==rtos_sys_processing_system7_0_0} -quiet] -quiet

# IP: bd/rtos_sys/ip/rtos_sys_axi_dma_0_0/rtos_sys_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rtos_sys_axi_dma_0_0 || ORIG_REF_NAME==rtos_sys_axi_dma_0_0} -quiet] -quiet

# IP: bd/rtos_sys/ip/rtos_sys_axi_gpio_0_0/rtos_sys_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rtos_sys_axi_gpio_0_0 || ORIG_REF_NAME==rtos_sys_axi_gpio_0_0} -quiet] -quiet

# IP: bd/rtos_sys/ip/rtos_sys_axi_gpio_1_0/rtos_sys_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rtos_sys_axi_gpio_1_0 || ORIG_REF_NAME==rtos_sys_axi_gpio_1_0} -quiet] -quiet

# IP: bd/rtos_sys/ip/rtos_sys_axis_data_fifo_0_0/rtos_sys_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rtos_sys_axis_data_fifo_0_0 || ORIG_REF_NAME==rtos_sys_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/rtos_sys/ip/rtos_sys_axis_data_fifo_1_0/rtos_sys_axis_data_fifo_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rtos_sys_axis_data_fifo_1_0 || ORIG_REF_NAME==rtos_sys_axis_data_fifo_1_0} -quiet] -quiet

# IP: bd/rtos_sys/ip/rtos_sys_axi_dma_1_0/rtos_sys_axi_dma_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rtos_sys_axi_dma_1_0 || ORIG_REF_NAME==rtos_sys_axi_dma_1_0} -quiet] -quiet

# IP: bd/rtos_sys/ip/rtos_sys_xlconcat_0_0/rtos_sys_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rtos_sys_xlconcat_0_0 || ORIG_REF_NAME==rtos_sys_xlconcat_0_0} -quiet] -quiet

# IP: bd/rtos_sys/ip/rtos_sys_axi_smc_0/rtos_sys_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rtos_sys_axi_smc_0 || ORIG_REF_NAME==rtos_sys_axi_smc_0} -quiet] -quiet

# IP: bd/rtos_sys/ip/rtos_sys_rst_ps7_0_50M_0/rtos_sys_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rtos_sys_rst_ps7_0_50M_0 || ORIG_REF_NAME==rtos_sys_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/rtos_sys/ip/rtos_sys_axi_mem_intercon_imp_xbar_0/rtos_sys_axi_mem_intercon_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rtos_sys_axi_mem_intercon_imp_xbar_0 || ORIG_REF_NAME==rtos_sys_axi_mem_intercon_imp_xbar_0} -quiet] -quiet

# IP: bd/rtos_sys/ip/rtos_sys_axi_mem_intercon_0/rtos_sys_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rtos_sys_axi_mem_intercon_0 || ORIG_REF_NAME==rtos_sys_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/rtos_sys/ip/rtos_sys_snow_0_0/rtos_sys_snow_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rtos_sys_snow_0_0 || ORIG_REF_NAME==rtos_sys_snow_0_0} -quiet] -quiet

# IP: bd/rtos_sys/ip/rtos_sys_white_0_0/rtos_sys_white_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rtos_sys_white_0_0 || ORIG_REF_NAME==rtos_sys_white_0_0} -quiet] -quiet

# IP: bd/rtos_sys/ip/rtos_sys_axi_mem_intercon_imp_auto_pc_0/rtos_sys_axi_mem_intercon_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rtos_sys_axi_mem_intercon_imp_auto_pc_0 || ORIG_REF_NAME==rtos_sys_axi_mem_intercon_imp_auto_pc_0} -quiet] -quiet

# IP: bd/rtos_sys/ip/rtos_sys_axi_mem_intercon_imp_auto_pc_1/rtos_sys_axi_mem_intercon_imp_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rtos_sys_axi_mem_intercon_imp_auto_pc_1 || ORIG_REF_NAME==rtos_sys_axi_mem_intercon_imp_auto_pc_1} -quiet] -quiet

# IP: bd/rtos_sys/ip/rtos_sys_axi_mem_intercon_imp_s00_mmu_0/rtos_sys_axi_mem_intercon_imp_s00_mmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rtos_sys_axi_mem_intercon_imp_s00_mmu_0 || ORIG_REF_NAME==rtos_sys_axi_mem_intercon_imp_s00_mmu_0} -quiet] -quiet

# IP: bd/rtos_sys/ip/rtos_sys_axi_mem_intercon_imp_s01_mmu_0/rtos_sys_axi_mem_intercon_imp_s01_mmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rtos_sys_axi_mem_intercon_imp_s01_mmu_0 || ORIG_REF_NAME==rtos_sys_axi_mem_intercon_imp_s01_mmu_0} -quiet] -quiet

# XDC: /home/ej3b/readoutsys/rtos_sys/rtos_sys.gen/sources_1/bd/rtos_sys/rtos_sys_ooc.xdc
